[package]
name = "codeswitch"
version = "0.1.0"
authors = ["Jonathan Lebon <jonathan@jlebon.com>"]
description = "Easily switch between different codebases."
edition = "2018"

[dependencies]
clap = "2"
# this is also used by clap
ansi_term = "0.11"
byteorder = "1"
openat = "0.1"
dirs = "1"
